packages:
  - examples/*
  - packages/*
  - apps/*
  - scripts
  - docs/*
  - tools/*
  - '!.context/*'
allowBuilds:
  '@parcel/watcher': true
  protobufjs: true
catalog:
  '@byc/rdno': 0.0.1-beta.1
  '@elysiajs/bearer': ^1.4.3
  '@elysiajs/cors': ^1.4.1
  '@elysiajs/eden': ^1.4.8
  '@elysiajs/node': ^1.4.5
  '@pinia/colada': ^1.0.0
  '@pinia/colada-devtools': ^0.4.5
  '@pinia/colada-plugin-auto-refetch': ^0.2.6
  '@standard-schema/spec': ^1.1.0
  '@tailwindcss/vite': ^4.2.2
  '@tsconfig/node24': ^24.0.4
  '@types/connect': ^3.4.38
  '@types/express': ^5.0.6
  '@types/node': '^24.12.0'
  '@types/pg': ^8.20.0
  '@visual-json/core': ^0.3.1
  '@visual-json/vue': ^0.3.1
  '@vitejs/plugin-vue': ^6.0.5
  '@viyuni/cookie-sync-client': ^0.0.3
  '@vue/tsconfig': '^0.9.1'
  '@vueuse/core': ^14.2.1
  arkenv: ^0.11.0
  arktype: ^2.2.0
  bilibili-live-ws: ^6.3.1
  chalk: ^5.6.2
  connect: ^3.7.0
  cookie: ^1.1.1
  croner: ^9.1.0
  daisyui: ^5.5.19
  dotenv: ^17.3.1
  drizzle-arktype: ^0.1.3
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.1
  elysia: ^1.4.28
  find-packages: ^10.0.4
  ky: ^1.14.3
  '@lucide/vue': ^1.7.0
  nitro: 3.0.260311-beta
  npm-run-all2: ^8.0.4
  pg: ^8.20.0
  pinia: ^3.0.4
  shiki: ^4.0.2
  tailwindcss: ^4.2.2
  tinyglobby: ^0.2.15
  typescript: ~5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.14
  'vite-plugin-vue-devtools': '^8.1.1'
  vite-plus: ^0.1.14
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  volta-json-ptr: 0.0.1-beta.3
  vue: 3.6.0-beta.9
  vue-router: ^5.0.4
  vue-tsc: ^3.2.6
  zod: ^4.3.6
overrides:
  '@vue/compat': beta
  '@vue/compiler-core': beta
  '@vue/compiler-dom': beta
  '@vue/compiler-sfc': beta
  '@vue/compiler-ssr': beta
  '@vue/compiler-vapor': beta
  '@vue/reactivity': beta
  '@vue/runtime-core': beta
  '@vue/runtime-dom': beta
  '@vue/runtime-vapor': beta
  '@vue/server-renderer': beta
  '@vue/shared': beta
  vite: 'catalog:'
  vitest: 'catalog:'
  vue: 3.6.0-beta.9
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
