packages:
  - 'services/*'
  - 'packages/*'
  - 'apps/*'
  - 'apps/games/*'
  - 'apps/tools/*'
  - 'scripts'
  - 'docs/*'
  - 'tools/*'
  - '!.context/*'
allowBuilds:
  '@parcel/watcher': true
  protobufjs: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.14
  vitest: npm:@voidzero-dev/vite-plus-test@latest
overrides:
  '@vue/compat': 'beta'
  '@vue/compiler-core': 'beta'
  '@vue/compiler-dom': 'beta'
  '@vue/compiler-sfc': 'beta'
  '@vue/compiler-ssr': 'beta'
  '@vue/compiler-vapor': 'beta'
  '@vue/reactivity': 'beta'
  '@vue/runtime-core': 'beta'
  '@vue/runtime-dom': 'beta'
  '@vue/runtime-vapor': 'beta'
  '@vue/server-renderer': 'beta'
  '@vue/shared': 'beta'
  vite: 'catalog:'
  vitest: 'catalog:'
  'vue': 'beta'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
