export interface FansMedal {
  /** 粉丝牌名称 */
  name: string;

  /** 粉丝牌等级 */
  level: number;

  /** 粉丝牌对应的直播间 ID, 0 表示不支持 */
  roomId: number;

  /**
   * 是否点亮
   * `1` 为点亮
   */
  isLighted: number;

  /** 如果是粉丝团套票, uid: 0 */
  uid?: number;

  guardType: GuardType;

  /**
   * 粉丝勋章类型，后加的属性，为了兼容性，因此为可选
   *
   * 0: 普通粉丝牌
   * 1: 大航海套票
   */
  type?: number;
}

export const GuardType = {
  /** 无 */
  None: 0,
  /** 总督 */
  Zongdu: 1,
  /** 提督 */
  Tidu: 2,
  /** 舰长 */
  Jianzhang: 3,
} as const;

export type GuardType = (typeof GuardType)[keyof typeof GuardType];

export const ViyuniEventType = {
  Message: 'message',
  Guard: 'guard',
  Gift: 'gift',
  SuperChat: 'superChat',
  SuperChatDelete: 'superChatDelete',
  LiveStart: 'liveStart',
  LiveEnd: 'liveEnd',
  LiveCutoff: 'liveCutoff',
  LiveWarning: 'liveWarning',
  LikesUpdate: 'likesUpdate',
  LikeClick: 'likeClick',
  EntryEffect: 'entryEffect',
} as const;

export type ViyuniEventType = (typeof ViyuniEventType)[keyof typeof ViyuniEventType];

/** B站直播命令类型 */
export const Cmd = {
  DANMU_MSG: 'DANMU_MSG',
  SEND_GIFT: 'SEND_GIFT',
  INTERACT_WORD: 'INTERACT_WORD',
  WATCHED_CHANGE: 'WATCHED_CHANGE',
  ENTRY_EFFECT: 'ENTRY_EFFECT',
  SUPER_CHAT_MESSAGE: 'SUPER_CHAT_MESSAGE',
  SUPER_CHAT_MESSAGE_JPN: 'SUPER_CHAT_MESSAGE_JPN',
  COMBO_SEND: 'COMBO_SEND',
  GUARD_BUY: 'GUARD_BUY',
  USER_TOAST_MSG: 'USER_TOAST_MSG',
  NOTICE_MSG: 'NOTICE_MSG',
  HOT_RANK_CHANGED: 'HOT_RANK_CHANGED',
  HOT_RANK_CHANGED_V2: 'HOT_RANK_CHANGED_V2',
  ONLINE_RANK_COUNT: 'ONLINE_RANK_COUNT',
  STOP_LIVE_ROOM_LIST: 'STOP_LIVE_ROOM_LIST',
  SPECIAL_GIFT: 'SPECIAL_GIFT',
  SUPER_CHAT_MESSAGE_DELETE: 'SUPER_CHAT_MESSAGE_DELETE',
  POPULARITY_RED_POCKET_NEW: 'POPULARITY_RED_POCKET_NEW',
  POPULARITY_RED_POCKET_START: 'POPULARITY_RED_POCKET_START',
  POPULARITY_RED_POCKET_WINNER_LIST: 'POPULARITY_RED_POCKET_WINNER_LIST',
  PREPARING: 'PREPARING',
  LIVE: 'LIVE',
  WARNING: 'WARNING',
  CUT_OFF: 'CUT_OFF',
  CHANGE_ROOM_INFO: 'CHANGE_ROOM_INFO',
  ROOM_CHANGE: 'ROOM_CHANGE',
  ROOM_REAL_TIME_MESSAGE_UPDATE: 'ROOM_REAL_TIME_MESSAGE_UPDATE',
  ROOM_SKIN_MSG: 'ROOM_SKIN_MSG',
  ROOM_SILENT_ON: 'ROOM_SILENT_ON',
  ROOM_SILENT_OFF: 'ROOM_SILENT_OFF',
  ROOM_BLOCK_MSG: 'ROOM_BLOCK_MSG',
  ROOM_ADMINS: 'ROOM_ADMINS',
  ROOM_ADMIN_ENTRANCE: 'room_admin_entrance',
  ROOM_ADMIN_REVOKE: 'ROOM_ADMIN_REVOKE',
  ONLINE_RANK_V2: 'ONLINE_RANK_V2',
  ONLINE_RANK_TOP3: 'ONLINE_RANK_TOP3',
  HOT_RANK_SETTLEMENT: 'HOT_RANK_SETTLEMENT',
  HOT_RANK_SETTLEMENT_V2: 'HOT_RANK_SETTLEMENT_V2',
  WIDGET_BANNER: 'WIDGET_BANNER',
  WIDGET_WISH_LIST: 'WIDGET_WISH_LIST',
  ANCHOR_LOT_CHECKSTATUS: 'ANCHOR_LOT_CHECKSTATUS',
  ANCHOR_LOT_START: 'ANCHOR_LOT_START',
  ANCHOR_LOT_END: 'ANCHOR_LOT_END',
  ANCHOR_LOT_AWARD: 'ANCHOR_LOT_AWARD',
  VIDEO_CONNECTION_JOIN_START: 'VIDEO_CONNECTION_JOIN_START',
  VIDEO_CONNECTION_MSG: 'VIDEO_CONNECTION_MSG',
  VIDEO_CONNECTION_JOIN_END: 'VIDEO_CONNECTION_JOIN_END',
  FULL_SCREEN_SPECIAL_EFFECT: 'FULL_SCREEN_SPECIAL_EFFECT',
  COMMON_NOTICE_DANMAKU: 'COMMON_NOTICE_DANMAKU',
  LIKE_INFO_V3_UPDATE: 'LIKE_INFO_V3_UPDATE',
  LIKE_INFO_V3_CLICK: 'LIKE_INFO_V3_CLICK',
  HOT_ROOM_NOTIFY: 'HOT_ROOM_NOTIFY',
  POPULAR_RANK_CHANGED: 'POPULAR_RANK_CHANGED',
  LIVE_INTERACTIVE_GAME: 'LIVE_INTERACTIVE_GAME',
  MULTI_VOICE_OPERATIN: 'MULTI_VOICE_OPERATIN',
  MULTI_VOICE_APPLICATION_USER: 'MULTI_VOICE_APPLICATION_USER',
  AREA_RANK_CHANGED: 'AREA_RANK_CHANGED',
  GOTO_BUY_FLOW: 'GOTO_BUY_FLOW',
  GUARD_HONOR_THOUSAND: 'GUARD_HONOR_THOUSAND',
  RECOMMEND_CARD: 'RECOMMEND_CARD',
  SYS_MSG: 'SYS_MSG',
  SHOPPING_CART_SHOW: 'SHOPPING_CART_SHOW',
  TRADING_SCORE: 'TRADING_SCORE',
  VOICE_JOIN_STATUS: 'VOICE_JOIN_STATUS',
  VOICE_JOIN_SWITCH: 'VOICE_JOIN_SWITCH',
  VOICE_JOIN_LIST: 'VOICE_JOIN_LIST',
  VOICE_JOIN_ROOM_COUNT_INFO: 'VOICE_JOIN_ROOM_COUNT_INFO',
  WIDGET_GIFT_STAR_PROCESS: 'WIDGET_GIFT_STAR_PROCESS',
  GIFT_STAR_PROCESS: 'GIFT_STAR_PROCESS',
  LIVE_MULTI_VIEW_CHANGE: 'LIVE_MULTI_VIEW_CHANGE',
  DANMU_AGGREGATION: 'DANMU_AGGREGATION',
  PK_BATTLE_START: 'PK_BATTLE_START',
  PK_BATTLE_END: 'PK_BATTLE_END',
  PK_BATTLE_FINAL_PROCESS: 'PK_BATTLE_FINAL_PROCESS',
  PK_BATTLE_PRE_NEW: 'PK_BATTLE_PRE_NEW',
  PK_BATTLE_PRE: 'PK_BATTLE_PRE',
  PK_BATTLE_PROCESS_NEW: 'PK_BATTLE_PROCESS_NEW',
  PK_BATTLE_PROCESS: 'PK_BATTLE_PROCESS',
  PK_BATTLE_SETTLE_USER: 'PK_BATTLE_SETTLE_USER',
  PK_BATTLE_SETTLE_V2: 'PK_BATTLE_SETTLE_V2',
  PK_BATTLE_SETTLE: 'PK_BATTLE_SETTLE',
  PK_BATTLE_START_NEW: 'PK_BATTLE_START_NEW',
  ACTIVITY_BANNER_CHANGE_V2: 'ACTIVITY_BANNER_CHANGE_V2',
  ACTIVITY_BANNER_CHANGE: 'ACTIVITY_BANNER_CHANGE',
  DM_INTERACTION: 'DM_INTERACTION',
  PLAY_TAG: 'PLAY_TAG',
  RANK_REM: 'RANK_REM',
  DANMU_TAG_CHANGE: 'DANMU_TAG_CHANGE',
  USER_TOAST_MSG_V2: 'USER_TOAST_MSG_V2',
  ONLINE_RANK_V3: 'ONLINE_RANK_V3',
} as const;

export type Cmd = (typeof Cmd)[keyof typeof Cmd];
